# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confname', models.CharField(max_length=32)),
                ('createtime', models.DateTimeField()),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createuser', models.CharField(max_length=32)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('createuser', models.CharField(max_length=32)),
                ('createtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=64)),
                ('os', models.CharField(max_length=32)),
                ('cpu', models.CharField(max_length=64)),
                ('mem', models.CharField(max_length=32)),
                ('virt', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='so.groups')),
                ('hostname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='so.hosts')),
            ],
        ),
        migrations.CreateModel(
            name='tasktable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=32)),
                ('args', models.CharField(max_length=128)),
                ('detail', models.TextField()),
                ('status', models.CharField(max_length=32)),
                ('createtime', models.DateTimeField()),
                ('createuser', models.CharField(max_length=32)),
                ('cuuid', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(through='so.relation', to='so.hosts'),
        ),
    ]
