# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userconf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zabbix_url', models.CharField(max_length=128)),
                ('zabbix_user', models.CharField(max_length=32)),
                ('zabbix_pass', models.CharField(max_length=128)),
                ('zabbix_token', models.CharField(max_length=128)),
                ('salt_url', models.CharField(max_length=128)),
                ('salt_user', models.CharField(max_length=32)),
                ('salt_pass', models.CharField(max_length=128)),
                ('salt_token', models.CharField(max_length=128)),
            ],
        ),
    ]
